version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: jmair-db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    container_name: jmair-app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      SPRING_NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      SPRING_KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
    ports:
      - "8080:8080"

volumes:
  db-data:
